# Generated by Django 3.2.7 on 2021-09-14 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CallOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=50)),
                ('call_date', models.CharField(max_length=20)),
                ('customer_number', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Զանգի պատվեր',
                'verbose_name_plural': 'Զանգի պատվերներ',
            },
        ),
        migrations.CreateModel(
            name='ContactWithUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': 'Կապ',
                'verbose_name_plural': 'Կապեր',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=50)),
                ('news_context', models.CharField(max_length=500)),
                ('news_image', models.ImageField(upload_to='NewsImages')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('in_home_page', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'նորություն',
                'verbose_name_plural': 'Նորություններ',
            },
        ),
        migrations.CreateModel(
            name='NewsHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_header_title', models.CharField(max_length=50)),
                ('news_header_context', models.CharField(max_length=500)),
                ('news_header_image', models.ImageField(upload_to='NewsHeaderImages')),
            ],
            options={
                'verbose_name': 'Նորության Էջի Վերևի հատված',
                'verbose_name_plural': 'Նորության Էջի Վերևի հատված',
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_title', models.CharField(max_length=50)),
                ('offer_context', models.CharField(max_length=500)),
                ('offer_image', models.ImageField(upload_to='OfferImages')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('last_date', models.DateField()),
                ('in_home_page', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'առաջարկ',
                'verbose_name_plural': 'Առաջարկներ',
            },
        ),
        migrations.CreateModel(
            name='Subscribe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
