# Generated by Django 3.2.7 on 2021-09-14 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculties',
            name='slug',
            field=models.SlugField(default=111, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
