# Generated by Django 3.2.7 on 2021-09-15 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_faculties_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultiesDescriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('context', models.TextField()),
                ('image', models.ImageField(upload_to='CourseDescription')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.facultycourse')),
            ],
        ),
        migrations.CreateModel(
            name='CourseVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='')),
                ('video_url', models.URLField()),
                ('description', models.TextField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.facultycourse')),
            ],
        ),
        migrations.CreateModel(
            name='CourseTeachers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='CourseTeachers')),
                ('facebook_link', models.URLField()),
                ('instagram_link', models.URLField()),
                ('twitter_link', models.URLField()),
                ('linkedin_link', models.URLField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.facultycourse')),
            ],
        ),
        migrations.CreateModel(
            name='CourseLevels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(choices=[(1, 'LevelOne'), (2, 'LevelTwo'), (3, 'LevelThree')])),
                ('name', models.CharField(max_length=100)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.facultycourse')),
            ],
        ),
        migrations.CreateModel(
            name='CourseInclude',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='CourseCourses')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.facultycourse')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCourses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('context', models.TextField()),
                ('period', models.CharField(max_length=30)),
                ('vacation', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='CourseCourses')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.facultycourse')),
            ],
        ),
        migrations.CreateModel(
            name='CourseComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.facultycourse')),
            ],
        ),
        migrations.CreateModel(
            name='CourseCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='CourseCertificate')),
                ('full_name', models.CharField(max_length=30)),
                ('context', models.TextField()),
                ('date', models.DateField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_page.facultycourse')),
            ],
        ),
    ]
